version: "3"

services:
  db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "4321:5432"
  app:
    build: .
    command: npm start
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      - db